name: TestZ

on:
  push:
    branches: Test_z_GA
  pull_request:
    branches: Test_z_GA

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_FULL: shahid1984/che-dashboard-next:next

    steps:
    - name: Checkout che-dashboard-next source code
      uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
    - name: Docker prepare
      run: docker image prune -a -f
    - name: Docker Login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" docker.io
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/s390x -t ${IMAGE_FULL}  -f apache.Dockerfile --push .
    - name: Docker Logout
      run: docker logout
